<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-19T14:18:52 IST" name="Default suite" finished-at="2025-08-19T14:19:31 IST" duration-ms="38619">
    <groups>
    </groups>
    <test started-at="2025-08-19T14:18:52 IST" name="Default test" finished-at="2025-08-19T14:19:31 IST" duration-ms="38619">
      <class name="VisualTesting.Applitest">
        <test-method signature="test()[pri:0, instance:VisualTesting.Applitest@74e52ef6]" started-at="2025-08-19T14:18:52 IST" name="test" finished-at="2025-08-19T14:19:31 IST" duration-ms="38546" status="FAIL">
          <exception class="com.applitools.eyes.exceptions.DiffsFoundException">
            <message>
              <![CDATA[Test 'Hello World Test' of 'Applitools Demo' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251646707452349/00000251646707452122?accountId=r1_V9prFekmK5tA9JN56fA__]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.applitools.eyes.exceptions.DiffsFoundException: Test 'Hello World Test' of 'Applitools Demo' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251646707452349/00000251646707452122?accountId=r1_V9prFekmK5tA9JN56fA__
at com.applitools.eyes.EyesRunner.logSessionResultsAndThrowException(EyesRunner.java:246)
at com.applitools.eyes.selenium.Eyes.lambda$close$0(Eyes.java:500)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:500)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:188)
at VisualTesting.Applitest.test(Applitest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- com.applitools.eyes.exceptions.DiffsFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- VisualTesting.Applitest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
